# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Na < Formula
  desc "CLI tool to effortlessly manage context aware nested shortcuts for shell commands."
  homepage "https://github.com/moyiz/na"
  version "0.0.9"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/moyiz/na/releases/download/v0.0.9/na_darwin_x86_64.tar.gz"
      sha256 "826dbb235a8df27307aa3d422a32f75126c6ad841c35196459082f9f49c91d0b"

      def install
        bin.install "na"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/moyiz/na/releases/download/v0.0.9/na_darwin_arm64.tar.gz"
      sha256 "445acff0ae4b432a4a7b531290e850be8908cbd2ceff9afee58f4a4a337c5c88"

      def install
        bin.install "na"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moyiz/na/releases/download/v0.0.9/na_linux_arm64.tar.gz"
      sha256 "a8d9b01a861b8871fe2a7713c7e6a76b122ab757b9d28e53815526b8644e0d16"

      def install
        bin.install "na"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moyiz/na/releases/download/v0.0.9/na_linux_x86_64.tar.gz"
      sha256 "72ba0b9299432969c6efa788c024c4af8121b1c0c4563d0bcdc794cd2d1b1b46"

      def install
        bin.install "na"
      end
    end
  end

  def post_install
    generate_completions_from_executable(bin/"na", "completion", shells: [:bash, :zsh, :fish])
  end
end
